server:
  port: 8080


spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    name: mybookstore
    url: jdbc:mysql://localhost:3306/mybookstore?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:xml/*Mapper.xml
  type-aliases-package: com.kyx1999.mybookstore.model
